# [AI-GEN] agent=Claude date=2026-09-21 task=Generate the compression grid configs and the Stage B/C run queues from one cell table
# reviewed-by: PENDING
#
# WHY THIS EXISTS
# ---------------
# The compression grid appears in four places: configs/compression/*.yaml, the Stage B
# queue, the Stage C queue, and the freeze cell list. Typing it four times guarantees a
# mismatch, and a mismatch between the frozen null's cell key and Stage C's cell key is
# not a typo you find quickly - Stage C refuses with a hash error and you go looking in
# the wrong place. So the table lives here once and everything else is generated.
#
# Regenerating is safe and idempotent EXCEPT for configs that a run has already
# referenced: those are IMMUTABLE (AI_RULES.md 1.2). The script refuses to overwrite a
# config whose content would change; delete it deliberately if you really mean to.
#
# Usage:
#   python deploy/shared/gen_cells.py configs      # write configs/compression/*.yaml
#   python deploy/shared/gen_cells.py queues       # write deploy/*/cells_*.txt
#   python deploy/shared/gen_cells.py all

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# --- THE GRID -------------------------------------------------------------------------
# 11 cells (proposal 3.2: RTN INT8->INT4, GPTQ, AWQ; magnitude + Wanda 0-60%).
# `cell` is the key used by frozen/{model}/{task}/{cell} and by stage_c.cell - it is the
# identity that ties a Stage C run to its frozen null. Never rename one after a freeze.
CELLS: list[dict] = [
    {"cell": "rtn_int8",     "family": "rtn",       "level": 8,    "kwargs": {"bits": 8}},
    {"cell": "rtn_int6",     "family": "rtn",       "level": 6,    "kwargs": {"bits": 6}},
    {"cell": "rtn_int4",     "family": "rtn",       "level": 4,    "kwargs": {"bits": 4}},
    {"cell": "gptq_int4",    "family": "gptq",      "level": 4,    "kwargs": {"bits": 4}},
    {"cell": "awq_int4",     "family": "awq",       "level": 4,    "kwargs": {"bits": 4}},
    {"cell": "magnitude_20", "family": "magnitude", "level": 0.2,  "kwargs": {"sparsity": 0.2}},
    {"cell": "magnitude_40", "family": "magnitude", "level": 0.4,  "kwargs": {"sparsity": 0.4}},
    {"cell": "magnitude_60", "family": "magnitude", "level": 0.6,  "kwargs": {"sparsity": 0.6}},
    {"cell": "wanda_20",     "family": "wanda",     "level": 0.2,  "kwargs": {"sparsity": 0.2}},
    {"cell": "wanda_40",     "family": "wanda",     "level": 0.4,  "kwargs": {"sparsity": 0.4}},
    {"cell": "wanda_60",     "family": "wanda",     "level": 0.6,  "kwargs": {"sparsity": 0.6}},
]

# Model/task coverage. Plan A = pythia only; Plan B = everything.
PLAN_A_MODELS = ["pythia160m", "pythia410m"]
PLAN_B_MODELS = ["pythia160m", "pythia410m", "gemma2_2b", "llama32_1b"]
TASKS = ["ioi", "greater_than"]

CONFIG_HEADER = """\
# [AI-GEN] agent=Claude date=2026-09-21 task=Compression grid cell (generated by deploy/shared/gen_cells.py)
# reviewed-by: PENDING
#
# Compression grid cell for Stage C (proposal 3.2). IMMUTABLE once referenced by a run
# (AI_RULES.md 1.2): if a Stage B freeze has been taken against this cell, changing any
# value here silently invalidates the frozen null that Stage C will compare against.
#
# NOTE ON HYDRA PACKAGING. This file populates cfg.compression.*. It deliberately does
# NOT set the root keys compression_family / compression_level / stage_c.cell, because
# configs/config.yaml lists `_self_` LAST in its defaults, so its own root values
# (compression_family: dense) would override anything a group file set. The run scripts
# therefore pass those root keys explicitly on the command line, generated from this same
# table so they cannot drift. See deploy/shared/gen_cells.py.
"""


def _fmt_kwargs(kwargs: dict) -> str:
    return "\n".join(f"  {k}: {v}" for k, v in kwargs.items())


def write_configs() -> None:
    out_dir = REPO / "configs" / "compression"
    out_dir.mkdir(parents=True, exist_ok=True)
    written, skipped = 0, 0
    for c in CELLS:
        path = out_dir / f"{c['cell']}.yaml"
        body = (
            f"{CONFIG_HEADER}\n"
            f"name: {c['cell']}\n"
            f"family: {c['family']}\n"
            f"level: {c['level']}\n"
            f"cell: {c['cell']}\n"
            f"compressor_kwargs:\n{_fmt_kwargs(c['kwargs'])}\n"
        )
        if path.exists() and path.read_text(encoding="utf-8") != body:
            print(f"  REFUSING to overwrite changed immutable config: {path.name}")
            skipped += 1
            continue
        path.write_text(body, encoding="utf-8")
        written += 1
    print(f"configs: {written} written, {skipped} refused, in {out_dir}")


def _overrides(model: str, task: str, c: dict, stage: str) -> str:
    """The exact Hydra override string for one cell. One source of truth."""
    common = (
        f"model={model} task={task} compression={c['cell']} "
        f"compression_family={c['family']} compression_level={c['level']} "
        f"+stage_c.cell={c['cell']} "
        + " ".join(f"+stage_c.compressor_kwargs.{k}={v}" for k, v in c["kwargs"].items())
    )
    return f"stage={stage} {common}"


def write_queues() -> None:
    plans = {
        REPO / "deploy" / "plan_a_local_pc": PLAN_A_MODELS,
        REPO / "deploy" / "plan_b_dgx_spark": PLAN_B_MODELS,
    }
    for plan_dir, models in plans.items():
        plan_dir.mkdir(parents=True, exist_ok=True)
        for stage in ("stageB", "stageC"):
            lines = [
                "# Generated by deploy/shared/gen_cells.py - do not hand-edit.",
                "# One cell per line; feed to the runner script. Comments and blanks are skipped.",
                f"# {len(models)} models x {len(TASKS)} tasks x {len(CELLS)} cells "
                f"= {len(models) * len(TASKS) * len(CELLS)} cells",
                "",
            ]
            for model in models:
                for task in TASKS:
                    for c in CELLS:
                        lines.append(_overrides(model, task, c, stage))
            path = plan_dir / f"cells_{stage.lower()}.txt"
            path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            n = len(models) * len(TASKS) * len(CELLS)
            print(f"queue: {path.relative_to(REPO)}  ({n} cells)")


def main() -> None:
    what = sys.argv[1] if len(sys.argv) > 1 else "all"
    if what in ("configs", "all"):
        write_configs()
    if what in ("queues", "all"):
        write_queues()
    if what not in ("configs", "queues", "all"):
        print(__doc__ or "usage: gen_cells.py [configs|queues|all]")
        sys.exit(2)


if __name__ == "__main__":
    main()
