# [AI-GEN] agent=Claude date=2026-09-14 task=Vendor the IOI and greater-than word lists from the pinned upstream releases
# reviewed-by: PENDING
#
# GENERATED FILE - do not edit by hand. Produced by extracting the lists from the pinned
# upstream sources with a script (not transcribed), asserting their lengths, and asserting
# the IOI lists are identical in both upstreams.
#
# Adapted from: https://github.com/ArthurConmy/Automatic-Circuit-Discovery @ bc99ace817974b5584b7ee203d596a8e2bbcd399, MIT
#   (acdc/ioi/ioi_dataset.py, acdc/greaterthan/utils.py;
#    licence: THIRD_PARTY_LICENSES/automatic-circuit-discovery-LICENSE.txt)
# which is itself "a very slightly edited version of"
#   https://github.com/redwoodresearch/Easy-Transformer @ ea15315dd24481e9e2ac5c3ef335d82907a1dc34, MIT
#   (easy_transformer/ioi_dataset.py; licence: THIRD_PARTY_LICENSES/easy-transformer-LICENSE.txt)
#   - the Wang et al. (ICLR 2023) IOI template set. NAMES, PLACES, OBJECTS and
#     BABA_TEMPLATES are byte-identical between the two upstreams (asserted at generation).
#   - NOUNS is the greater-than noun list (ACDC's operationalisation of Hanna et al. 2023,
#     arXiv:2305.00586).

"""Word lists for the real IOI and greater-than prompt sets.

These are the UPSTREAM pools. They were built for GPT-2's tokenizer, so a task must filter
them against the tokenizer of the model under test and record the usable counts - under
Pythia (GPT-NeoX tokenizer) 11 of the 99 names and 8 of the 120 nouns are multi-token.
"""

from __future__ import annotations

ACDC_COMMIT = 'bc99ace817974b5584b7ee203d596a8e2bbcd399'
EASY_TRANSFORMER_COMMIT = 'ea15315dd24481e9e2ac5c3ef335d82907a1dc34'

#: sha256 of each upstream source file these lists were extracted from.
UPSTREAM_SHA256: dict[str, str] = {'acdc/ioi/ioi_dataset.py': '0c76473307e6815ebd31e9c3586fb4b775fa065eea0be45ace8b90e3eb34b7fe', 'acdc/greaterthan/utils.py': '3d64f5bb0a87efafd7f97896bc598c749f3cc0c7e4bbef48d80cbf001111d986', 'easy_transformer/ioi_dataset.py': '94a72de90e426382322fd690669024a0d2d4bd72a45ed9ce820a99ae9173d231'}

NAMES: tuple[str, ...] = (
    'Michael',
    'Christopher',
    'Jessica',
    'Matthew',
    'Ashley',
    'Jennifer',
    'Joshua',
    'Amanda',
    'Daniel',
    'David',
    'James',
    'Robert',
    'John',
    'Joseph',
    'Andrew',
    'Ryan',
    'Brandon',
    'Jason',
    'Justin',
    'Sarah',
    'William',
    'Jonathan',
    'Stephanie',
    'Brian',
    'Nicole',
    'Nicholas',
    'Anthony',
    'Heather',
    'Eric',
    'Elizabeth',
    'Adam',
    'Megan',
    'Melissa',
    'Kevin',
    'Steven',
    'Thomas',
    'Timothy',
    'Christina',
    'Kyle',
    'Rachel',
    'Laura',
    'Lauren',
    'Amber',
    'Brittany',
    'Danielle',
    'Richard',
    'Kimberly',
    'Jeffrey',
    'Amy',
    'Crystal',
    'Michelle',
    'Tiffany',
    'Jeremy',
    'Benjamin',
    'Mark',
    'Emily',
    'Aaron',
    'Charles',
    'Rebecca',
    'Jacob',
    'Stephen',
    'Patrick',
    'Sean',
    'Erin',
    'Jamie',
    'Kelly',
    'Samantha',
    'Nathan',
    'Sara',
    'Dustin',
    'Paul',
    'Angela',
    'Tyler',
    'Scott',
    'Katherine',
    'Andrea',
    'Gregory',
    'Erica',
    'Mary',
    'Travis',
    'Lisa',
    'Kenneth',
    'Bryan',
    'Lindsey',
    'Kristen',
    'Jose',
    'Alexander',
    'Jesse',
    'Katie',
    'Lindsay',
    'Shannon',
    'Vanessa',
    'Courtney',
    'Christine',
    'Alicia',
    'Cody',
    'Allison',
    'Bradley',
    'Samuel',
)

PLACES: tuple[str, ...] = (
    'store',
    'garden',
    'restaurant',
    'school',
    'hospital',
    'office',
    'house',
    'station',
)

OBJECTS: tuple[str, ...] = (
    'ring',
    'kiss',
    'bone',
    'basketball',
    'computer',
    'necklace',
    'drink',
    'snack',
)

BABA_TEMPLATES: tuple[str, ...] = (
    'Then, [B] and [A] went to the [PLACE]. [B] gave a [OBJECT] to [A]',
    'Then, [B] and [A] had a lot of fun at the [PLACE]. [B] gave a [OBJECT] to [A]',
    'Then, [B] and [A] were working at the [PLACE]. [B] decided to give a [OBJECT] to [A]',
    'Then, [B] and [A] were thinking about going to the [PLACE]. [B] wanted to give a [OBJECT] to [A]',
    'Then, [B] and [A] had a long argument, and afterwards [B] said to [A]',
    'After [B] and [A] went to the [PLACE], [B] gave a [OBJECT] to [A]',
    'When [B] and [A] got a [OBJECT] at the [PLACE], [B] decided to give it to [A]',
    'When [B] and [A] got a [OBJECT] at the [PLACE], [B] decided to give the [OBJECT] to [A]',
    'While [B] and [A] were working at the [PLACE], [B] gave a [OBJECT] to [A]',
    'While [B] and [A] were commuting to the [PLACE], [B] gave a [OBJECT] to [A]',
    'After the lunch, [B] and [A] went to the [PLACE]. [B] gave a [OBJECT] to [A]',
    'Afterwards, [B] and [A] went to the [PLACE]. [B] gave a [OBJECT] to [A]',
    'Then, [B] and [A] had a long argument. Afterwards [B] said to [A]',
    'The [PLACE] [B] and [A] went to had a [OBJECT]. [B] gave it to [A]',
    'Friends [B] and [A] found a [OBJECT] at the [PLACE]. [B] gave it to [A]',
)

NOUNS: tuple[str, ...] = (
    'abduction',
    'accord',
    'affair',
    'agreement',
    'appraisal',
    'assaults',
    'assessment',
    'attack',
    'attempts',
    'campaign',
    'captivity',
    'case',
    'challenge',
    'chaos',
    'clash',
    'collaboration',
    'coma',
    'competition',
    'confrontation',
    'consequence',
    'conspiracy',
    'construction',
    'consultation',
    'contact',
    'contract',
    'convention',
    'cooperation',
    'custody',
    'deal',
    'decline',
    'decrease',
    'demonstrations',
    'development',
    'disagreement',
    'disorder',
    'dispute',
    'domination',
    'dynasty',
    'effect',
    'effort',
    'employment',
    'endeavor',
    'engagement',
    'epidemic',
    'evaluation',
    'exchange',
    'existence',
    'expansion',
    'expedition',
    'experiments',
    'fall',
    'fame',
    'flights',
    'friendship',
    'growth',
    'hardship',
    'hostility',
    'illness',
    'impact',
    'imprisonment',
    'improvement',
    'incarceration',
    'increase',
    'insurgency',
    'invasion',
    'investigation',
    'journey',
    'kingdom',
    'marriage',
    'modernization',
    'negotiation',
    'notoriety',
    'obstruction',
    'operation',
    'order',
    'outbreak',
    'outcome',
    'overhaul',
    'patrols',
    'pilgrimage',
    'plague',
    'plan',
    'practice',
    'process',
    'program',
    'progress',
    'project',
    'pursuit',
    'quest',
    'raids',
    'reforms',
    'reign',
    'relationship',
    'retaliation',
    'riot',
    'rise',
    'rivalry',
    'romance',
    'rule',
    'sanctions',
    'shift',
    'siege',
    'slump',
    'stature',
    'stint',
    'strikes',
    'study',
    'test',
    'testing',
    'tests',
    'therapy',
    'tour',
    'tradition',
    'treaty',
    'trial',
    'trip',
    'unemployment',
    'voyage',
    'warfare',
    'work',
)

